FROM nginx:latest

ARG DOCKERFILE_VERSION="1.1.1"
ARG VERSION_ODIN="2.0.1"
ARG VERSION_THOR="1.3.4"

ENV DOCKERFILE_VERSION="$DOCKERFILE_VERSION"
ENV VERSION_ODIN="$VERSION_ODIN"
ENV VERSION_THOR="$VERSION_THOR"

COPY index.html /usr/share/nginx/html/
EXPOSE 80